### ISSUE TITLE
Is django-sendfile still maintained ?

### ISSUE THREAD

**Issue by C4ptainCrunch** [johnsensible/django-sendfile#29]
There are some unresolved issues and pending pull requests with no answer.
Are you still maintaining this project ?

**Comment by johnsensible** [comment]
Yes and no.

This project is used in a couple of our clients projects, but I've not needed to do any work on it myself.  So it's not been high on my priorities.

Also the recentish tickets pull request/issues happen to have occurred after my second child was born (beginning on Sept 2014).  So coupled with that and work I've not had a chance to deal with them.

If anyone wants to fork the project and take over, that's fine with me of course (that's the beauty of open source).  For a relatively small (niche) project like this though I'd say a few months inactivity doesn't mean it's dead.

**Comment by stevelacey** [comment]
@johnsensible can't see anyone that stands out – but forking is a messy solve, choosing someone who's enthused about the project and adding them as a collaborator would be the ideal.

**Comment by johnsensible** [comment]
@stevelacey I guess to rephrase that.  It's not that I'm not maintaining this project.  It's just that:

a) I'm busy (work + life)
b) It's a niche library that is for the most part complete
c) Non of the issues that have been reported recently currently affect me

Which all conspires to mean that I've not dealt with anything on this project for a while (and several others too).

So what I need:

a) Pull requests for fixes
b) Help with and explanation of issues
c) Time

Sorry if I seem a bit rude about this.  For some reason I've had lots of people asking if projects are maintained or not recently.  I know to some people that six months seems like a long time, but it's really not...
