### ISSUE TITLE
RemovedInDjango19Warning about importlib when using Django 1.8

### ISSUE THREAD

**Issue by lars-tiede** [johnsensible/django-sendfile#30]
When running Django 1.8, I get this warning (repeatedly):

```
py-env/local/lib/python2.7/site-packages/sendfile/__init__.py:23: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```

Suggested fix: just import importlib (and not django.utils.importlib), it's included in Python 2.7. Check https://docs.djangoproject.com/fr/1.8/releases/1.7/#deprecated-features-1-7, search for "importlib".

**Comment by pmdarrow** [comment]
This was fixed in https://github.com/johnsensible/django-sendfile/pull/37. This issue can be closed.

**Comment by lars-tiede** [comment]
Nice :)
