### ISSUE TITLE
Nginx doesn't like URL escaped file paths

### ISSUE THREAD

**Issue by FreakyDug** [johnsensible/django-sendfile#35]
Since 0.3.6, sendfile has been URL escaping the file path before setting the X-Accel-Redirect header. This seems to confuse nginx, leading to it being unable to find a file with an @ in the name because it is looking for a file with a %40 in it.

**Comment by johnsensible** [comment]
Think this is basically the same as issue #26.

Basically the fix that was added to deal with unicode characters is using urlquote instead of encoding the characters properly...

**Comment by johnsensible** [comment]
Ok, I've just pushed a fix into master.  Could you give that a test for me and make sure it actually works please?  Then I'll package it up for PyPi etc as a new release.

**Comment by FreakyDug** [comment]
I don't know how I missed #26, it does look like the same bug. I'll try out your fix and report back.
