### ISSUE TITLE
mod_wsgi backend broken on Django 1.8

### ISSUE THREAD

**Issue by kaedroho** [johnsensible/django-sendfile#36]
On Django 1.7 and before, the ``Location`` header that is returned by the mod_wsgi backend is just the path to the file (eg: ``/media/documents/mydoc.pdf``).

On Django 1.8, it has ``http://`` appended to the beginning. So the above path has now changed to ``http:///media/documents/mydoc.pdf``.

**Comment by johnsensible** [comment]
I'm guessing this is something that Django is doing?  If it's changed that is.

Looking at the code for the backend would seem to show we just set the header without the http:

https://github.com/johnsensible/django-sendfile/blob/master/sendfile/backends/mod_wsgi.py

Though it will also use whatever you put in your SENDFILE_URL setting.  Are you sure you don't have http:// in there?

**Comment by joshcartme** [comment]
I'm also running into issues with Django 1.8 and the mod_wsgi backend.  Under 1.8, everything that gets sent has a size of 0 bytes.  Reverting to 1.7.9 fixes the issue.

To test a bit I did something like this:

    response = sendfile(request, download.path, attachment=True)
    print response

The result in 1.7 and 1.8 was the same:

    Content-length: 4040899
    Content-Type: application/zip
    Location: /static/downloads/download.zip
    Content-Disposition: attachment; filename="download.zip"

I was curious and printed the request in each case and it looks like the request has changed significantly in Django 1.8.  Under 1.7 it appears to be a dictionary with a lot of stuff, under 1.8 all that gets printed is:

    <WSGIRequest: GET '/a/path?download'>

My guess is that the internal redirect stuff is no longer working with Django 1.8 style requests.

Here are some details on the changes to requests, https://docs.djangoproject.com/en/1.8/releases/1.8/#requests-and-responses

I'm not sure where to go with this from here.  Thanks!

**Comment by joshcartme** [comment]
I did a little more digging, and think I figured it out.  This needs to be added to the mod_wsg backend sendfile:

    request.build_absolute_uri = lambda location: location

Something must have changed in Django 1.8 that is causing build_absolute_uri to be used in a different place or work differently.  Adding that gets rid of the http:// from the location header.

**Comment by joshcartme** [comment]
Fixed here, https://github.com/johnsensible/django-sendfile/pull/40

**Comment by johnsensible** [comment]
Ok, have merged that in.  Looks like similar to what was being done before with get_host(), but Django was now involving the schema as well.

Hopefully will manage a new release in a bit.

**Comment by joshcartme** [comment]
Thanks, yeah very similar to what was done before.

I'm still not exactly sure what changed in Django to necessitate what I did.  I just was reading the docs and it looked promising so I tried it =)

**Comment by johnsensible** [comment]
I actually dug into the django code a bit.  Looks like they were trying to deal with locations that started with // which would be protocol relative.  They'd then try to put in the scheme + host as part of that.  As I was already monkey-patching the get_host method, it was just adding the http:// on it's own.

**Comment by johnsensible** [comment]
OK I've released 0.3.9 which fixes this now.  That's up on PyPi too:

https://pypi.python.org/pypi/django-sendfile/0.3.9

**Comment by joshcartme** [comment]
Thanks :+1:
