### ISSUE TITLE
Release 0.3.8

### ISSUE THREAD

**Issue by pmdarrow** [johnsensible/django-sendfile#39]
Would love the fix that landed in #37. Do you plan on cutting a 0.3.8 release any time soon or are you waiting for some more changes to come in?

**Comment by johnsensible** [comment]
Yeah, guess I was just sort of waiting to see if anything else turned up.  I'll see about doing a release.

**Comment by johnsensible** [comment]
Ok, that's on PyPi now:

https://pypi.python.org/pypi/django-sendfile/0.3.8
