### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by drakkan** [johnsensible/django-sendfile#41]
sendfile depends on Unidecode that is GPL this means that sendfile and all other software that import it should be GPL too. Since unidecode is used only here:

https://github.com/johnsensible/django-sendfile/blob/master/sendfile/__init__.py#L80

would be possible to remove this dependency?

**Comment by drakkan** [comment]
unidecode dependency seems required to support old browsers

https://github.com/johnsensible/django-sendfile/commit/312170c217bd42369804bb551369758e34b0d0bd
http://kbyanc.blogspot.hk/2010/07/serving-file-downloads-with-non-ascii.html

maybe it could be done optional, for example:

1) make an explicit setting to not set filename as ascii and so not use unidecode
2) use a try except and don't set filename as ascii if unidecode is not installed

what do you think about?

**Comment by johnsensible** [comment]
I guess it could be possible to remove the dependency.  The Unidecode package does appear to do a pretty good job, but if we just want to do something basic then something like this might work well enough:

    import unicodedata
    unicodedata.normalize('NFKD', attachment_filename).encode('ascii','ignore')

from here:
http://stackoverflow.com/questions/2365411/python-convert-unicode-to-ascii-without-errors

Care to submit a patch/pull request for it?

**Comment by drakkan** [comment]
created a pull request, thanks!

**Comment by johnsensible** [comment]
Merged it and made a new version (0.3.10), which is now also on PyPi.

Thank you.
