### ISSUE TITLE
Is status  really "Beta"?

### ISSUE THREAD

**Issue by guettli** [johnsensible/django-sendfile#48]
We use this module since several years and it works perfectly.

Is status (according to pypi page) really "Beta"?

**Comment by johnsensible** [comment]
In some respects it's probably not really "beta" - I've had it in 
production for a long time too.  Though there are a couple of lingering 
issues with unicode and things.

Mostly though it's just to indicate that (more strongly) that it *may 
not* work perfectly and to be careful.

**Comment by guettli** [comment]
ok, it is our decision. I would call it "stable" :-)

**Comment by guettli** [comment]
The pypi status of django-sendfile is still "Beta": https://pypi.org/project/django-sendfile/

@johnsensible what do you think about this now (5 years later)?

**Comment by moggers87** [comment]
@guettli this project hasn't been touched in 4 years. I think it's safe to say it's been abandoned. FWIW, I have made a fork here: https://github.com/moggers87/django-sendfile2

**Comment by guettli** [comment]
@moggers87 thank you for taking this over!
